### ISSUE TITLE
player.hasItem override

### ISSUE THREAD

**Issue by andrewstucki** [AlexNisnevich/untrusted#104]
Check out [my gist for level 13](https://gist.github.com/anonymous/724f7a986872f7bc475e#file-untrusted-lvl13-solution-js-L27). A number of levels, including 11, 12, 13, and 20 can be (mostly) solved by overriding this method (solving 20 this way also includes coupling this with a phone callback and generated teleporters).

**Comment by pppery** [comment]
This was patched by 14df29f782bd29f56bc6a68c71517087832cdd50
