### ISSUE TITLE
Overriding map lets you win many levels

### ISSUE THREAD

**Issue by NickCis** [AlexNisnevich/untrusted#114]
If you can edit code before blocks, and/or other objects are placed. You can place them, then, override the map object.
Here is the code:

``` javascript
map.placeObject(40, 12, 'exit'); //Exit is placed

var a = map,
    map = {};

for(var k in a)
    map[k] = a[k];

for(var i=0, k, keys= [
    "defineObject",
    "placeObject",
    "getHeight",
    "getWidth",
    "placePlayer"
]; k = keys[i]; i++)
    map[k] = function(){};
```

I really haven't read the game code in order to know how "map" is setted, but, I suppose that you treate it as a global (what's to say, it is a property of the window object). If you set it like this, the user won't be able to modify it:

``` javascript
Object.defineProperty(window, "map", {
    get : function() {
        return _realMap
    },
    set: function(){},
    enumerable: false,
    configurable: false
});
```

In addition, properties and methods of the map object could be setted as not enumerable, this would prevent the user from copying some necesary methods to start the game.

**Comment by pppery** [comment]
`map` isn't actually a global variable, but instead a parameter to the `startLevel` function.  Also, I'm not entirely convinced this is a bug, given that overriding `map` like that will cause validation (which gets a fresh copy of the map unaffected by your override) to fail.
