### ISSUE TITLE
Calling unexposed methods

### ISSUE THREAD

**Issue by anfit** [AlexNisnevich/untrusted#121]
Regardless of undescore prevention circumvention it is still possible to call most 'priviledged' methods directly, e.g. the following snippet triggers _destroy for most robots:

``` javascript
var objects = map.getDynamicObjects();
for (var i = 0; i < objects.length; i++) {
    var object = objects[i];
    j = 0;
    for (prop in object) {
        if (j===4) {
            object[prop]();
        }
        j++;
    }
}
```

Note that there is no need to address a method by name, so attempting to stamp out underscores is pretty much pointless...

**Comment by pppery** [comment]
This no longer works in recent versions of Untrusted.
