### ISSUE TITLE
gaps in API docs

### ISSUE THREAD

**Issue by AlexNisnevich** [AlexNisnevich/untrusted#158]
map.writeStatus, canvas.lineTo, some object properties missing

And should we include built-in classes like String and Number?

-- henke37 on Octagonal Pasture

**Comment by pppery** [comment]
> map.writeStatus
Fixed by ea0c437db3cad99bd72f10f05b5a6acaf3fd86a2
> canvas.lineTo
Fixed by 7cd94afd0a14082c6451286b263af5bd1d009e8f
> map.finalLevel
Wouldn't documenting this property defeat the entire point of level 21?
> map.validateAtLeastXLines
Fixed by #455
