### ISSUE TITLE
In level 15, accidentally deleted but unsaved/unexecuted code becomes uneditable

### ISSUE THREAD

**Issue by liligga** [AlexNisnevich/untrusted#198]
Say, I have intered some code(' Hello !!!') in editable area:

```
map.defineObject('water', {
        'symbol': '░',
        'color': '#44f',
        'onCollision': function (player) {
            player.killedBy(' Hello !!!');
        }
    });
```

Then, execute, then delete my own code totally, like so:

```
map.defineObject('water', {
        'symbol': '░',
        'color': '#44f',
        'onCollision': function (player) {
            player.killedBy();
        }
    });
```

Then without executing reloaded the page. Suddenly my 

```
' Hello !!!'
```

becomes uneditable. Resetting the level helps. But I thought, it wouldn't be useless if I report. Didn't try other levels, only for 15th.

**Comment by pppery** [comment]
I can't reproduce this either.
