### ISSUE TITLE
shuffle with [1,2,3].sort(function(){return 0.5 - Math.random()})

### ISSUE THREAD

**Issue by pavel-kolesnikov** [AlexNisnevich/untrusted#240]
Just a suggestion: shuffle with Array.prototype.sort 

```
function shuffle(a) {
   a.sort(function(){return 0.5 - Math.random()});
}
```

**Comment by datibbaw** [comment]
Have a look at [this visualisation](http://bost.ocks.org/mike/shuffle/compare.html) of shuffle methods.
