### ISSUE TITLE
Donation link should make a more honest plea

### ISSUE THREAD

**Issue by konklone** [AlexNisnevich/untrusted#268]
The donation link in the bottom right corner says "Help us pay for bandwidth!", but you're hosted on GitHub Pages. You pay $0 for all the bandwidth you incur. 

Suggested replacements:
- Help support the game!
- Help us add new levels!
- Reward us for making a good game with $!

And/or, rotate randomly between these and others. Hell, A/B test it if you want, Wikipedia-style. :smile:

**Comment by pppery** [comment]
This entire issue was obsoleted by 6ebf1905a058cd9ceeea35ae81626e35a23cc52e
