### ISSUE TITLE
Verification not triggered when picking up object

### ISSUE THREAD

**Issue by tpwrules** [AlexNisnevich/untrusted#275]
The verification routines don't run before an object is picked up. My solution to level 14 was `player.removeItem(''+map.placeObject(20,7,'theAlgorithm')+'');`. I can pick up the duplicate algorithm and get to the exit without triggering the verification. I only get caught if another dynamic object interaction happens before the fake is picked up.

**Comment by pppery** [comment]
Cannot reproduce.
