### ISSUE TITLE
Spoiler Alert! Spoiler Alert! How to get the blue key

### ISSUE THREAD

**Issue by mathdude314** [AlexNisnevich/untrusted#315]
So, I got the blue key by setting up a control pad. There were four spaces (which I colored blue with `setSquareColor()`) that moved the robot up, down, left, right. I'm not sure if this was the intended solution, but at least I had full control of where the robot moved.

I'd like to see if anyone else had a simpler solution.

**Comment by AlexNisnevich** [comment]
Nice! A few people had similar approaches: https://github.com/AlexNisnevich/untrusted/blob/master/solutions/13_robotMaze.md
