### ISSUE TITLE
SECURITY ERROR! SECURITY ERROR!

### ISSUE THREAD

**Issue by ghost** [AlexNisnevich/untrusted#316]
I found that the following code beat `threeKeys.js`:

``` javascript
    map["val"+"idateExactlyXManyObjects"] = function() {return true;};
    map["val"+"idateAtMostXObjects"] = function() {return true;};
    map.placeObject(8, 2, 'exit');
    map.placeObject(8, 4, 'redKey');
    map.placeObject(8, 5, 'greenKey');
    map.placeObject(8, 3, 'blueKey');
```

You cleverly avoided defining `map.validateExactlyXManyObjects`, but my trick here gets around it. I could technically beat almost every level with this. Just not some of the highly restrictive ones like the first `theAlgorithm` level and the "choose the mode of your death" one. In fact, it's an easy solution to the boss level.

**Comment by mathdude314** [comment]
And, I can really circumvent stuff by doing
```javascript
map["v"+"a"+"l"+"i"+"d"+"a"+"t"+"e"+"E"+"x"+"a"+"c"+"t"+"l"+"y"+"X"+"M"+"a"+"n"+"y"+"O"+"b"+"j"+"e"+"c"+"t"+"s"] = function() {return true;}```

**Comment by AlexNisnevich** [comment]
Strange, I would expect [`detectTampering`](https://github.com/AlexNisnevich/untrusted/blob/master/scripts/validate.js#L327) to prevent this.

**Comment by mathdude314** [comment]
Maybe use `Object.defineProperty`?
Like this:
```javascript
var obj = {};
Object.defineProperty(obj, "answer", {
    get: function() {return 42;},
    set: function() { throw "You cannot change the Answer!"; }
});
```
In your case:
```javascript
var _validateExactlyXManyObjects = function() {
    code code code
};
Object.defineProperty(map, "validateExactlyXManyObjects", {
    get: function() {
        return _validateExactlyXManyObjects;
    }
    set: function() { throw "Tampering detected!"; }
);
```

The reason `detectTampering` fails is it looks for the string `validate`, not `"v"+"a"+"l"+"i"+`..., so you can overwrite functions.

**Comment by mathdude314** [comment]
Is this fixed? Because I need a way to do it in `crispsContest.jsx`...

**Comment by mathdude314** [comment]
@AlexNisnevich I tried today and it's still there... I'll find a way to do it in `crispsContest.jsx` if this is not fixed.

**Comment by luka-zitnik** [comment]
threeKeys.jsx is a bonus level.

And all bonus levels have super menu activated, https://github.com/AlexNisnevich/untrusted/blob/master/scripts/game.js#L387-L390.

In this sense, https://github.com/AlexNisnevich/untrusted/blob/master/scripts/ui.js#L220.

And when the super menu is activated, tampering detection is skipped, https://github.com/AlexNisnevich/untrusted/blob/master/scripts/validate.js#L328-L331.

I think this is all fine, :sparkles: in other words.
