### ISSUE TITLE
Why is the 10th bonus level not there?

### ISSUE THREAD

**Issue by mathdude314** [AlexNisnevich/untrusted#318]
@AlexNisnevich I was playing this and noticed there are 10 levels in the bonus folder but only 9 are playable. I can't see `wallsWithEyes.jsx` in the selection screen.

**Comment by mathdude314** [comment]
@AlexNisnevich Ok, so `wallsWithEyes.jsx` doesn't work, and I'm also finding it a bit hard to make a level (I had an idea about a drone factory?). Any advice?

**Comment by AlexNisnevich** [comment]
Oops, looks like Untrusted hadn't been rebuilt in a while. `wallsWithEyes.jsx` should be there now, sorry for the wait.

You still need any help with your own level? What's giving you trouble?

**Comment by mathdude314** [comment]
Oh, well it's just that I forgot how to test it. Never mind, I know now.
