### ISSUE TITLE
"Never Minding" your way out of 02_theEmptyRoom.jsx

### ISSUE THREAD

**Issue by ghost** [AlexNisnevich/untrusted#324]
``` javascript
throw "Never mind.";
```

Wins bonus level 2 right away. I wish it had verification, or maybe the terminal opens another gate you have to pass. Or, you need to get the, say, blue key and then you go through the exit.

**Comment by pppery** [comment]
I'm not inclined to consider this a bug, given that it was added to the solutions file and is entirely specific to the level (unlike my other patches that invalidated solutions by fixing holes that are not specific to one level but instead could be used to hack the entire game).
