### ISSUE TITLE
Overwriting player.killedBy

### ISSUE THREAD

**Issue by mathdude314** [AlexNisnevich/untrusted#327]
@AlexNisnevich 
I noticed that in some levels it's possible to simply set `player.killedBy` to `function() {}`, voiding the following levels:
<ul>
<li>05_minesweeper.jsx</li>
<li>06_drones101.jsx</li>
<li>09_fordingTheRiver.jsx</li>
<li>10_ambush.jsx</li>
<li>15_exceptionalCrossing.jsx</li>
<li>16_lasers.jsx</li>
<li><strong>20_bossFight.jsx</strong></li>
<li>02_theEmptyRoom.jsx</li>
<li>03_theCollapsingRoom.jsx</li>
<li>04_theGuard.jsx</li>
<li>pushme.jsx</li>
<li>trapped.jsx</li>
</ul>
To solve these levels you simply define `player.killedBy = function() {}`, though `15_exceptionalCrossing.jsx` is tricky.
The fix, of course, is to make `player.killedBy` be unable to get tampered with.

**Comment by AlexNisnevich** [comment]
Hey @mathdude314 , this should only be possible after you've already beaten the game. Normally, Untrusted prevents functions from being tampered with, but `detectTampering` is disabled after you beat `20_bossFight` and activate the super menu (this is to make modifying script files from within the super menu more fun).
