### ISSUE TITLE
Level 7: setPhoneCallback lose focus, can't move @

### ISSUE THREAD

**Issue by alexsun** [AlexNisnevich/untrusted#334]
for resolve need use "^2 Toggle Focus" two times, look like bug, because with default source of level have same behaviour. Browser: Safari

Thanks for nice game

**Comment by drshrey** [comment]
Just to confirm the bug you experienced, you're saying you can't move @ without pressing ^2 two times, on Safari?

**Comment by alexsun** [comment]
can't explain and reproduce now, have checked again a level it is playable to complete
