### ISSUE TITLE
Game is not loading

### ISSUE THREAD

**Issue by lucianopf** [AlexNisnevich/untrusted#343]
It was working fine weeks ago but lately the game is not loading =/

![image](https://cloud.githubusercontent.com/assets/8251208/8640761/82bad3fa-28da-11e5-8e14-40a8b0977ee0.png)

**Comment by AlexNisnevich** [comment]
Oops, looks like there was a git conflict issue earlier today. Does it work now?

**Comment by Camel-lot** [comment]
yep, thank you! :+1:

**Comment by AlexNisnevich** [comment]
Ok, sorry about that!

**Comment by lucianopf** [comment]
Np mate!
