### ISSUE TITLE
Make isn't working

### ISSUE THREAD

**Issue by faysvas** [AlexNisnevich/untrusted#350]
I got this error when running make

"makefile 14:File mods/default/intro.js not found!. Stop."

I fixed that error by providing "example_mod" instead of "default" in line 12 of the makefile but then I get another error:

Building level fileβ??\t\t\t\c
process_begin: CreateProcess(C:\untrusted\compile_levels.sh, ./compile_levels.sh
 example_mod, ...) failed.
make (e=193): Error 193
make: *** [release] Error 193

**Comment by faysvas** [comment]
I'm using windows 8.1if that helps

**Comment by AlexNisnevich** [comment]
`compile_levels.sh` isn't going to work on Windows, unfortunately.
