### ISSUE TITLE
You can't use window but navigator work

### ISSUE THREAD

**Issue by mylainos** [AlexNisnevich/untrusted#351]
The use of window is forbidden but navigator isn't.
You can finish level like the 12 with it :
https://gist.github.com/anonymous/fc3ce1626ffe282662c9

**Comment by pppery** [comment]
I don't entirely see why this is a bug. All your solution is doing is using `navigator` to store data across functions calls. The ability to store data across calls is entirely intentional, and is even used in uneditable portions of Level 20.
