### ISSUE TITLE
What happened to the bonus levels?

### ISSUE THREAD

**Issue by mathdude314** [AlexNisnevich/untrusted#354]
So... been a while, checked to see if there were any new bonus levels. And... there were _less_!
Only `pushme.jsx` and `trapped.jsx` remain. Something must have happened. Maybe someone did a Pull Request on something they accidentally destroyed the bonus file, or deliberately destroyed it and accidentally included it in the merge.

After looking through the file, there *are* more levels. They're just not accessible. (Like with `wallsWithEyes.jsx`.)

**Comment by AlexNisnevich** [comment]
Sorry about that! I'm not sure why the bonus levels were broken for a while - somehow an old version of the game was being served.

All 15 bonus levels are back now, and we're planning on adding another few over the next week. Stay tuned!
