### ISSUE TITLE
L14 solution?

### ISSUE THREAD

**Issue by 3-0663651** [AlexNisnevich/untrusted#357]
```javascript
            player.removeItem(''+(player.removeItem=function(){})); ('');
```

Oh why do you allow tampering `player.removeItem`?
(I beat level 21, but level 22 progress is reset for some reason — I've had to replay the game like three times, but each time my code was saved...)

Oh I managed to get all four keys AND the Algorithm... and looted the secondary places...

**Comment by AlexNisnevich** [comment]
Huh, progress shouldn't be reset at level 22. I'll take a look.

**Comment by 3-0663651** [comment]
Oh no it's not the reset — that was my fault, I just realized. I just don't like that you can override `player.removeItem`.

**Comment by AlexNisnevich** [comment]
Overriding `removeItem` is a fun alternative solution :+1:
