### ISSUE TITLE
player.canMove() undefined?

### ISSUE THREAD

**Issue by 3-0663651** [AlexNisnevich/untrusted#358]
Oh I wanted to be able to make some interesting level, but yet, it happened that `player.canMove` isn't defined for some reason. Safari 8.0.6. Oh, I'm totes not sure why.

**Comment by AlexNisnevich** [comment]
That's weird. Could you give the code that caused this error?

**Comment by 3-0663651** [comment]
Oh it fixed itself when I upgraded to Safari 9.0.1.
