### ISSUE TITLE
You can place another 'player' on the map. Intended?

### ISSUE THREAD

**Issue by dramforever** [AlexNisnevich/untrusted#383]
For example on level 6, write this into the black area:
```
map.placeObject(map.getWidth()-10,14,'player')
```
Then trick the drone so that it hopelessly goes for the 'fake' player instead of yourself.

Is this the intended behaviour?

**Comment by AlexNisnevich** [comment]
Yeah! 

It's not useful in most levels, but it certainly helps in level 6.
