### ISSUE TITLE
Validation can be disabled via this

### ISSUE THREAD

**Issue by zhykzhykzhyk** [AlexNisnevich/untrusted#385]
Press right and win the level (for most levels)

``` javascript
var b = this;
b['vali' + 'dateLevel'] = function(){}
(this)['on' + 'Exit'] = function () { return true; }
map.placeObject(map.getPlayer().getX() + 1, map.getPlayer().getY(), 'exit');
```

**Comment by pppery** [comment]
Although, I just realized this was added to the solutions file for level 20, meaning it may be intentional.

**Comment by pppery** [comment]
Aploogies for creating five different commits referencing this issue; I somehow managed to get my fork I was using to develop patches very disorganized and failed to recover properly.
