### ISSUE TITLE
Level 14 bugged, can only edit inside string

### ISSUE THREAD

**Issue by KelsonBall** [AlexNisnevich/untrusted#404]
On level 14 I can only edit the code between the `'` marks, even though the `'` marks are not in the red. This prevents me from using any of the listed solutions, as anything I type is a string and I can't write any code.
I'm on opera. Here is a screenshot of my console.

![image](https://user-images.githubusercontent.com/7193540/35882423-ffd92790-0b38-11e8-9a5a-a19730b3e947.png)

Here is an example of my cursor being by the `'` but not being able to either **add characters or backspace**
![image](https://user-images.githubusercontent.com/7193540/35882486-32d76788-0b39-11e8-83b2-da7a88fde89a.png)

**Comment by AlexNisnevich** [comment]
Hi Kelson,

There is no bug with level 14. It is intentional that you can only edit the code within quotes.

Good luck!

Alex
