### ISSUE TITLE
Color changes, can't pass red gate (lvl7)

### ISSUE THREAD

**Issue by rgtiom** [AlexNisnevich/untrusted#456]
Hi, might be me doing something wrong but on lvl7 I inputted the following in phoneCallback
```
var player = map.getPlayer();
        col = {
        	red:'#F00',
            yellow:'#FF0',
            green:'#0F0'
        };
       
		if(player.atLocation(20, 12)|player.atLocation(21, 12)){
        	player.setColor(col.green);
        }else if(player.atLocation(23, 12)|player.atLocation(32, 12)){
        	player.setColor(col.red);
        }else if(player.atLocation(26, 12)|player.atLocation(35, 12)){
        	player.setColor(col.yellow);
        }
```

This changed the colour of my player but would not allow me to pass red gate. Sorry if I've missed something - I know there are other ways of solving this puzzle (Browser Chrome 76.0.3809.100)

**Comment by AlexNisnevich** [comment]
Hi @rgtiom, note that the color locks are case-sensitive. Try `'#f00'`, `'#ff0'`, and `'#0f0'` instead.
