### ISSUE TITLE
Boss Level not clear what to do

### ISSUE THREAD

**Issue by Whitedoteu** [AlexNisnevich/untrusted#484]
HI is just played through the game.  (Really liked it :) )

I had to look-up a solution for the Boss-Level. 
I couldn't figure out that I needed to use "projectiles" to destroy the Boss. 
After knowing this it seems trivial but I tried a lot of things and read the API. 
After about 30 min I decided to look up a solution. 

I think a hint with a comment like: "onDestroy by Projectile"
Would really help improve this level.

**Comment by pppery** [comment]
The API does say "If true, this object destroys any dynamic object (or player) that it collides with, and is itself destroyed when it collides with anything." Did you find something unclear about that?

**Comment by pppery** [comment]
Besides, it would make no thematic sense for there to be a hint in the comments, since the boss itself is the same person who wrote the level files and taunted you in comments in the previous five levels.

**Comment by Whitedoteu** [comment]
Hi, 
of course, you are right. In theory, all the information is there. 
And it is possible that I just wasn't able to connect the dots. 

For me, the projectile was a "Boss item". 
And the Player can't use "boss items".
Looking back at it I never even considered using it.

I think it was the first level where you did use something the enemy did use directly against them. And that's why I struggled. 

PS: I don't expect a solution for my issue. I just want to raise the issue I had for maybe some considerations in the future if the issue surfaces again.

**Comment by pppery** [comment]
Untrusted is all about being different, and messing with typical game expectations. There are no hidden rules like "you can't use boss items" (well, there aren't until level 21 at least).

**Comment by Whitedoteu** [comment]
I'm struggling with bringing my thoughts to paper. 

So let me try a different explanation. 
Every Level has some kind of gimmick you have to overcome or manage to solve the level. 

When starting the final level and seeing the projectiles drop I thought the gimmick is dodge or remove or invalidate the projectiles. 

After learning I have to kill the boss I never saw the projectiles as an option because the gimmick was to deal with them. 
That I did not have to deal with them if I kill the boss therefore never came to mind and I never found the solution. 

There is a possibility that the issue only happens to me. Because of my thought process or that I first thought of "World Hardest Game" when I saw the final level. 

But maybe some kind of hint like "Space Invaders can shoot back" or something that hints towards using projectiles and fighting back could have brought me back on track solving the level. 

PS: You're faster with your replay than I can type my thoughts up.
Your right it is all there and open to see i just wanted to give feedback :) 
Thanks for your answers :)

**Comment by neunenak** [comment]
The fundamental gameplay mechanic of Untrusted is that any code the player writes that executes in the browser and has the result of letting the player progress past the level counts as a solution to that level. We did our best to rule out really easy/obvious solutions, but beyond that whatever a player thinks of that gets past the level is fair game. We thought about possible solutions a player might try when coming up with levels, but there isn't one specific gimmick that is the "intended solution" for any particular level, and we think it's great if people come up with solutions to levels that never occurred to us when we were developing it.
